# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'MobADDemo.xcworkspace'

abstract_target 'MobADDemo' do
    pod 'mob_adsdk','2.1.5'
    pod 'mob_adsdk/MobADPlat/BUD'
    pod 'mob_adsdk/MobADPlat/GDT'

    target 'MobADDemo' do
      project 'MobADDemo.xcodeproj'

    end
    
end


